-- ============================================================
-- Expense OS — Official Supabase Database Schema & Migration (v4.0 Unified)
-- ============================================================
-- Copy and paste this script into your Supabase Dashboard:
-- https://app.supabase.com -> SQL Editor -> New Query -> Run
-- ============================================================

-- 1. CREATE ALL 9 CORE TABLES IF NOT EXISTS

-- Table 1: Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  display_name TEXT,
  full_name TEXT,
  gender TEXT DEFAULT 'male',
  avatar_url TEXT,
  phone TEXT DEFAULT '',
  job TEXT DEFAULT '',
  country TEXT DEFAULT 'United States',
  bio TEXT DEFAULT '',
  currency TEXT DEFAULT 'INR',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT profiles_user_id_unique UNIQUE (user_id)
);

-- Table 2: Expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL DEFAULT 0,
  category TEXT DEFAULT 'Miscellaneous',
  description TEXT DEFAULT '',
  payment TEXT DEFAULT 'Cash',
  date TEXT DEFAULT '',
  tags JSONB DEFAULT '[]'::jsonb,
  receipt_url TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 3: Budgets
CREATE TABLE IF NOT EXISTS public.budgets (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  category TEXT DEFAULT 'ALL',
  amount NUMERIC DEFAULT 0,
  month TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 4: Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#34D399',
  icon TEXT DEFAULT 'fa-tag',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 5: Subscriptions & Recurring Bills
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  amount NUMERIC DEFAULT 0,
  category TEXT DEFAULT 'Services & Subscriptions',
  date TEXT DEFAULT '',
  billing_cycle TEXT DEFAULT 'Monthly',
  next_due TEXT DEFAULT '',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 6: Split Bills (Group Expenses)
CREATE TABLE IF NOT EXISTS public.split_bills (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  total_amount NUMERIC DEFAULT 0,
  date TEXT DEFAULT '',
  category TEXT DEFAULT 'Food & Dining',
  payer TEXT DEFAULT 'You',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 7: Split Bill Members
CREATE TABLE IF NOT EXISTS public.split_bill_members (
  id TEXT PRIMARY KEY,
  bill_id TEXT REFERENCES public.split_bills(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  share_amount NUMERIC DEFAULT 0,
  is_paid BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 8: Export Templates
CREATE TABLE IF NOT EXISTS public.export_templates (
  template_id TEXT PRIMARY KEY DEFAULT 'default_executive_template',
  brand_name TEXT DEFAULT 'Expense OS Financial Operating System',
  logo_url TEXT DEFAULT '',
  header_title TEXT DEFAULT 'EXECUTIVE FINANCIAL STATEMENT & AUDIT REPORT',
  footer_note TEXT DEFAULT 'Generated by Expense OS — Confidential Financial Record',
  default_currency TEXT DEFAULT 'INR',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Table 9: User Data (Master Aggregate Snapshot)
CREATE TABLE IF NOT EXISTS public.user_data (
  user_id TEXT PRIMARY KEY,
  budget NUMERIC DEFAULT 0,
  expenses JSONB DEFAULT '[]'::jsonb,
  subscriptions JSONB DEFAULT '[]'::jsonb,
  incomes JSONB DEFAULT '[]'::jsonb,
  currency TEXT DEFAULT 'INR',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. INSERT DEFAULT EXPORT TEMPLATE
INSERT INTO public.export_templates (template_id, brand_name, header_title, footer_note, default_currency)
VALUES ('default_executive_template', 'Expense OS Financial Operating System', 'EXECUTIVE FINANCIAL STATEMENT & AUDIT REPORT', 'Generated by Expense OS — Confidential Financial Record', 'INR')
ON CONFLICT (template_id) DO NOTHING;

-- 3. ENSURE ALL COLUMNS EXIST (IDEMPOTENT MIGRATIONS FOR EXISTING SCHEMAS)
DO $$ 
BEGIN
    -- user_data migrations
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_data' AND column_name='incomes') THEN
        ALTER TABLE public.user_data ADD COLUMN incomes JSONB DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_data' AND column_name='currency') THEN
        ALTER TABLE public.user_data ADD COLUMN currency TEXT DEFAULT 'INR';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_data' AND column_name='budget') THEN
        ALTER TABLE public.user_data ADD COLUMN budget NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_data' AND column_name='expenses') THEN
        ALTER TABLE public.user_data ADD COLUMN expenses JSONB DEFAULT '[]'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_data' AND column_name='subscriptions') THEN
        ALTER TABLE public.user_data ADD COLUMN subscriptions JSONB DEFAULT '[]'::jsonb;
    END IF;

    -- profiles migrations
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='phone') THEN
        ALTER TABLE public.profiles ADD COLUMN phone TEXT DEFAULT '';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='job') THEN
        ALTER TABLE public.profiles ADD COLUMN job TEXT DEFAULT '';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='country') THEN
        ALTER TABLE public.profiles ADD COLUMN country TEXT DEFAULT 'United States';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='bio') THEN
        ALTER TABLE public.profiles ADD COLUMN bio TEXT DEFAULT '';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='currency') THEN
        ALTER TABLE public.profiles ADD COLUMN currency TEXT DEFAULT 'INR';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='updated_at') THEN
        ALTER TABLE public.profiles ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now();
    END IF;
END $$;

-- 4. ENABLE ROW LEVEL SECURITY (RLS) ON ALL 9 TABLES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.split_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.split_bill_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.export_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_data ENABLE ROW LEVEL SECURITY;

-- 5. CREATE RLS POLICIES FOR ALL 9 TABLES

-- Profiles Policies
DROP POLICY IF EXISTS "Users can manage own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can select own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can delete own profile" ON public.profiles;
CREATE POLICY "Users can manage own profile" ON public.profiles FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Expenses Policies
DROP POLICY IF EXISTS "Users can manage own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can select own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
CREATE POLICY "Users can manage own expenses" ON public.expenses FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Budgets Policies
DROP POLICY IF EXISTS "Users can manage own budgets" ON public.budgets;
DROP POLICY IF EXISTS "Users can select own budgets" ON public.budgets;
DROP POLICY IF EXISTS "Users can insert own budgets" ON public.budgets;
DROP POLICY IF EXISTS "Users can update own budgets" ON public.budgets;
DROP POLICY IF EXISTS "Users can delete own budgets" ON public.budgets;
CREATE POLICY "Users can manage own budgets" ON public.budgets FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Categories Policies
DROP POLICY IF EXISTS "Users can manage own categories" ON public.categories;
DROP POLICY IF EXISTS "Users can select own categories" ON public.categories;
DROP POLICY IF EXISTS "Users can insert own categories" ON public.categories;
DROP POLICY IF EXISTS "Users can update own categories" ON public.categories;
DROP POLICY IF EXISTS "Users can delete own categories" ON public.categories;
CREATE POLICY "Users can manage own categories" ON public.categories FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Subscriptions Policies
DROP POLICY IF EXISTS "Users can manage own subscriptions" ON public.subscriptions;
CREATE POLICY "Users can manage own subscriptions" ON public.subscriptions FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Split Bills Policies
DROP POLICY IF EXISTS "Users can manage own split bills" ON public.split_bills;
CREATE POLICY "Users can manage own split bills" ON public.split_bills FOR ALL USING (auth.uid() = user_id OR user_id IS NULL) WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Split Bill Members Policies
DROP POLICY IF EXISTS "Users can manage own split bill members" ON public.split_bill_members;
CREATE POLICY "Users can manage own split bill members" ON public.split_bill_members FOR ALL USING (true) WITH CHECK (true);

-- Export Templates Policies (Public readable/customizable)
DROP POLICY IF EXISTS "Public template access" ON public.export_templates;
CREATE POLICY "Public template access" ON public.export_templates FOR ALL USING (true) WITH CHECK (true);

-- User Data Policies
DROP POLICY IF EXISTS "Users can manage their own data" ON public.user_data;
CREATE POLICY "Users can manage their own data" ON public.user_data FOR ALL USING (true) WITH CHECK (true);

-- 6. ENABLE REALTIME SYNC ON ALL RELEVANT TABLES
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'user_data') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.user_data;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'expenses') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.expenses;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'budgets') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.budgets;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'subscriptions') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.subscriptions;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'profiles') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'categories') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.categories;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'split_bills') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.split_bills;
  END IF;
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

-- 7. STORAGE BUCKETS & POLICIES
INSERT INTO storage.buckets (id, name, public) 
VALUES ('receipts', 'receipts', false), ('avatars', 'avatars', true) 
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Users can read own receipts" ON storage.objects;
CREATE POLICY "Users can read own receipts" ON storage.objects FOR SELECT USING (bucket_id = 'receipts' AND auth.uid()::text = (storage.foldername(name))[1]);

DROP POLICY IF EXISTS "Users can upload own receipts" ON storage.objects;
CREATE POLICY "Users can upload own receipts" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'receipts' AND auth.uid()::text = (storage.foldername(name))[1]);

DROP POLICY IF EXISTS "Users can delete own receipts" ON storage.objects;
CREATE POLICY "Users can delete own receipts" ON storage.objects FOR DELETE USING (bucket_id = 'receipts' AND auth.uid()::text = (storage.foldername(name))[1]);

-- 8. CONVENIENCE REPORTING & EXPORT VIEWS

CREATE OR REPLACE VIEW public.vw_user_expenses_export AS
SELECT 
    ud.user_id,
    ud.currency,
    exp->>'id' AS transaction_id,
    exp->>'date' AS transaction_date,
    exp->>'category' AS category,
    exp->>'description' AS description,
    exp->>'payment' AS payment_method,
    (exp->>'amount')::NUMERIC AS amount
FROM public.user_data ud,
LATERAL jsonb_array_elements(ud.expenses) AS exp;

CREATE OR REPLACE VIEW public.vw_user_subscriptions_export AS
SELECT 
    ud.user_id,
    ud.currency,
    sub->>'id' AS subscription_id,
    sub->>'name' AS bill_name,
    sub->>'category' AS category,
    (sub->>'amount')::NUMERIC AS monthly_cost,
    sub->>'date' AS billing_date
FROM public.user_data ud,
LATERAL jsonb_array_elements(ud.subscriptions) AS sub;

CREATE OR REPLACE VIEW public.vw_admin_all_user_expenses AS
SELECT 
    ud.user_id AS user_account_id,
    exp->>'date' AS transaction_date,
    exp->>'category' AS category,
    exp->>'description' AS description,
    exp->>'payment' AS payment_method,
    (exp->>'amount')::NUMERIC AS amount_spent,
    ud.currency AS base_currency,
    ud.updated_at AS last_synced_at
FROM public.user_data ud
LEFT JOIN LATERAL jsonb_array_elements(ud.expenses) AS exp ON true
ORDER BY ud.updated_at DESC, exp->>'date' DESC;

CREATE OR REPLACE VIEW public.vw_admin_user_summaries AS
SELECT 
    ud.user_id AS user_account_id,
    ud.currency AS base_currency,
    ud.budget AS monthly_budget_cap,
    jsonb_array_length(ud.expenses) AS total_expenses_count,
    jsonb_array_length(ud.subscriptions) AS total_subscriptions_count,
    jsonb_array_length(ud.incomes) AS total_incomes_count,
    ud.updated_at AS last_active_time
FROM public.user_data ud
ORDER BY ud.updated_at DESC;
